deployment:
  replicaCount: 1
config: 
  input:
    label: consumer_input_rmq
    amqp_0_9:
      #urls: 
      #  - amqp://enix:password@mq:5672/
      queue: "q1"
    processors:
      - log:
          level: INFO
          fields_mapping: "root = this"

  pipeline:
    processors:
      - branch:
          request_map: |
            root.prompt = this.prompt
            root.stop = "\n"
            root.temperature = 0.8
          processors:
            - http:
                url: http://textsynth:8020/v1/engines/mistral_7B_q4/completions
                verb: POST
                timeout: 300s
          result_map: |
            root.completion = this.text

  output:
    label: insert_db
    sql_insert:
      driver: "postgres"
      #dsn: postgres://user:password@hostname/dbname
      table: messages
      columns: [ submitted_at, generated_at, city, prompt, completion, uuid ]
      args_mapping: root = [ this.submitted_at, now(), this.city, this.prompt, this.completion, this.uuid ]
resources: 
  limits:
    cpu: 1
    memory: 500M
  requests:
    cpu: 0.1
    memory: 500M

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
metrics:
  prometheus:
    add_process_metrics: true
    add_go_metrics: true
serviceMonitor:
  enabled: true

